mysql:
  addr: 127.0.0.1
  port: 3306
  password: "123456"
  username: root
  dbname: user
  charset: utf8mb4
  parsetime: "True"
  loc: Local
# user:pass@tcp(127.0.0.1:3306)/dbname?charset=utf8mb4&parseTime=True&loc=Local